import React from 'react'

const page = () => {
  return (
    <div className='h-full py-10 font-poppins'>
      <h1 className='text-2xl md:text-4xl font-bold text-center '>
        Privacy Policy

      </h1>
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-8">Last updated: September 28, 2024</p>

        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        <p className="mb-8">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>

        <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mb-2">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside mb-8">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Zenlect AI, KOLKATA, WEST BENGAL, INDIA.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: West Bengal, India.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Zenlect, accessible from <a href="https://zenlect.com" className="text-blue-500 underline">zenlect.com</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>

        <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc list-inside mb-8">
          <li>Email address</li>
        </ul>

        <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="mb-4">
          Usage Data may include information such as Your Device&quot;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="mb-4">
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p className="mb-8">
          We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
        </p>

        <h3 className="text-xl font-semibold mb-2">Tracking Technologies and Cookies</h3>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
          <li>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on the <a href="https://www.termsfeed.com/blog/cookies/" className="text-blue-500 underline">TermsFeed website</a> article.</li>
        </ul>

        <p className="mb-4">
          We use both Session and Persistent Cookies for the purposes set out below:
        </p>

        <div className="mb-8">
          <h4 className="text-lg font-semibold mb-2">Necessary / Essential Cookies</h4>
          <ul className="list-disc list-inside">
            <li><strong>Type:</strong> Session Cookies</li>
            <li><strong>Administered by:</strong> Us</li>
            <li><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
          </ul>
        </div>

        <div className="mb-8">
          <h4 className="text-lg font-semibold mb-2">Cookies Policy / Notice Acceptance Cookies</h4>
          <ul className="list-disc list-inside">
            <li><strong>Type:</strong> Persistent Cookies</li>
            <li><strong>Administered by:</strong> Us</li>
            <li><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</li>
          </ul>
        </div>

        <div className="mb-8">
          <h4 className="text-lg font-semibold mb-2">Functionality Cookies</h4>
          <ul className="list-disc list-inside">
            <li><strong>Type:</strong> Persistent Cookies</li>
            <li><strong>Administered by:</strong> Us</li>
            <li><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
          </ul>
        </div>

        <h2 className="text-2xl font-semibold mb-4">Use of Your Personal Data</h2>
        <p className="mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc list-inside mb-8">
          <li><strong>To provide and maintain our Service:</strong> Including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.</li>
          <li><strong>To provide You with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</strong></li>
          <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
          <li><strong>To comply with a legal obligation:</strong> To comply with applicable laws, regulations, and legal requests.</li>
        </ul>

        <h2 className="text-2xl font-semibold mb-4">Retention of Your Personal Data</h2>
        <p className="mb-4">
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p className="mb-4">
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Transfer of Your Personal Data</h2>
        <p className="mb-4">
          Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
        </p>
        <p className="mb-4">
          If You are located outside India and choose to provide information to Us, please note that we transfer the data, including Personal Data, to India and process it there.
        </p>
        <p className="mb-4">
          Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
        </p>
        <p className="mb-4">
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Disclosure of Your Personal Data</h2>

        <h3 className="text-xl font-semibold mb-2">Business Transactions</h3>
        <p className="mb-4">
          If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>

        <h3 className="text-xl font-semibold mb-2">Legal Requirements</h3>
        <p className="mb-4">
          The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h2 className="text-2xl font-semibold mb-4">Security of Your Personal Data</h2>
        <p className="mb-4">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security
        </p>

        <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights</h2>
        <p className="mb-4">
          Depending on your location, you may have the following data protection rights:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>The right to access – You have the right to request copies of your Personal Data.</li>
          <li>The right to rectification – You have the right to request that we correct any information you believe is inaccurate or incomplete.</li>
          <li>The right to erasure – You have the right to request that we erase your Personal Data, under certain conditions.</li>
          <li>The right to restrict processing – You have the right to request that we restrict the processing of your Personal Data, under certain conditions.</li>
          <li>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
          <li>The right to object – You have the right to object to our processing of your Personal Data, under certain conditions.</li>
        </ul>

        <h2 className="text-2xl font-semibold mb-4">Links to Other Websites</h2>
        <p className="mb-4">
          Our Service may contain links to other websites that are not operated by Us. If you click on a third-party link, you will be directed to that third party&quot;s site. We strongly advise you to review the Privacy Policy and terms of service of every site you visit.
        </p>
        <p className="mb-4">
          We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Children&quot;s Privacy</h2>
        <p className="mb-4">
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from
          children without verification of parental consent, we take steps to remove that information from our servers.

        </p>

        <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
        <p className="mb-4">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
        <p className="mb-4">
          If you have any questions about this Privacy Policy, please contact us:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>By email:<a className='text-blue-500' href="mailto:support@zenlect.ai"> support@zenlect.ai</a></li>
        </ul>

      </div>






    </div>
  )
}

export default page